name: FractureX's translation module

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # Descargar los últimos 2 commits para poder comparar

      - name: Set up Git
        run: |
          git fetch --tags
          git config --global user.email "shaquille.montero.vergel123@gmail.com"
          git config --global user.name "GitHub Actions"

      - name: Get the latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null || echo "v0.0.0")
          echo "tag=$latest_tag" >> $GITHUB_ENV

      - name: Get the list of changed files
        id: changes
        run: |
          new_files=$(git diff --name-status HEAD~1 HEAD | grep '^A' | awk '{print $2}' | paste -sd "," -)
          modified_files=$(git diff --name-status HEAD~1 HEAD | grep '^M' | awk '{print $2}' | paste -sd "," -)
          new_directories=$(git diff --dirstat=files,0 HEAD~1 HEAD | awk '{print $2}' | grep '/$' | paste -sd "," -)
          echo "new_files=$new_files" >> $GITHUB_ENV
          echo "modified_files=$modified_files" >> $GITHUB_ENV
          echo "new_directories=$new_directories" >> $GITHUB_ENV

      - name: Calculate new version
        id: calculate_version
        run: |
          current_version=${{ env.tag }}
          major=$(echo $current_version | cut -d. -f1 | cut -c2-)
          minor=$(echo $current_version | cut -d. -f2)
          patch=$(echo $current_version | cut -d. -f3)

          new_major=$major
          new_minor=$minor
          new_patch=$patch

          # Check for new directories (considered as new features, thus MINOR update)
          if [ "${{ env.new_directories }}" != "" ]; then
            new_minor=$((minor + 1))
            new_patch=0
          fi

          # Check for new files (considered as new features, thus MINOR update)
          if [ "${{ env.new_files }}" != "" ]; then
            new_minor=$((minor + 1))
            new_patch=0
          fi

          # Check for modified files
          if [ "${{ env.modified_files }}" != "" ]; then
            is_major_change=false
            # Loop through each modified file and determine if it contains breaking changes
            IFS=',' read -r -a files <<< "${{ env.modified_files }}"
            for file in "${files[@]}"; do
              if grep -q 'def ' "$file"; then
                # Simulate checking for breaking changes in function signatures
                if grep -Eq 'def .+\(.+\):' "$file"; then
                  is_major_change=true
                  break
                fi
              fi
            done

            if [ "$is_major_change" = true ]; then
              new_major=$((major + 1))
              new_minor=0
              new_patch=0
            else
              if [ "$new_minor" -ne "$minor" ]; then
                new_patch=0
              else
                new_patch=$((patch + 1))
              fi
            fi
          fi

          new_version="v${new_major}.${new_minor}.${new_patch}"
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Create new tag
        env:
          PAT: ${{ secrets.PAT }}  # Utilizar el PAT desde los secretos
        run: |
          new_version=${{ env.new_version }}
          git tag $new_version
          git push https://x-access-token:${PAT}@github.com/${{ github.repository }}.git $new_version

      - name: Generate badge
        run: |
          new_version=${{ env.new_version }}
          curl -o badge.svg "https://img.shields.io/badge/version-${new_version}-blue"
          echo "Badge created."

      - name: Commit badge
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'github-actions'
          author_email: 'actions@github.com'
          message: 'Update version badge'
          add: 'badge.svg'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}  # Utilizar el PAT para hacer commits
